In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

In [5]:
 df=pd.read_csv("diabetes.csv")

In [6]:
df.head()


,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [7]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
df.fillna(df.mean(), inplace=True)   # for numeric
df.fillna(df.mode().iloc[0], inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
plt.boxplot(df)

{'whiskers': [<matplotlib.lines.Line2D at 0x18a50ea4190>,
 'caps': [<matplotlib.lines.Line2D at 0x18a50ea4410>,
 'boxes': [<matplotlib.lines.Line2D at 0x18a50d1bed0>,
 'medians': [<matplotlib.lines.Line2D at 0x18a50ea4690>,
 'fliers': [<matplotlib.lines.Line2D at 0x18a50ea47d0>,
 'means': []}

In [12]:
def outlier_capping(df,column):
    Q1=df[column].quantile(0.25)
    Q3=df[column].quantile(0.75)
    IQR=Q3-Q1
    lower_extreme=Q1-1.5*IQR
    upper_extreme=Q3+1.5*IQR
    df[column]=df[column].apply(lambda x:lower_extreme if x<lower_extreme else upper_extreme if x>upper_extreme else x)
for col in df.select_dtypes(['int','float']).columns:
    outlier_capping(df,col)

In [13]:
plt.boxplot(df)
    

{'whiskers': [<matplotlib.lines.Line2D at 0x18a50f2d090>,
 'caps': [<matplotlib.lines.Line2D at 0x18a50f2d310>,
 'boxes': [<matplotlib.lines.Line2D at 0x18a50f2cf50>,
 'medians': [<matplotlib.lines.Line2D at 0x18a50f2d590>,
 'fliers': [<matplotlib.lines.Line2D at 0x18a50f2d6d0>,
 'means': []}

In [17]:
for i in df:
    plt.figure(figsize=(10,6))
    sns.histplot(df)
    plt.title(f' histogram {i}')
    plt.show()

In [15]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
num_cols

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

## Create pair plot

In [16]:
sns.pairplot(df[num_cols], hue="Outcome")
plt.suptitle("Pair Plot of Numerical Features")
plt.show()

In [18]:
target=df["Outcome"]
feature=df.drop("Outcome", axis=1)

In [19]:
x_train,x_test,y_train,y_test=train_test_split(feature,target,test_size=0.3,random_state=44)

In [20]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(537, 8)
(231, 8)
(537,)
(231,)


In [21]:
sl=StandardScaler()


In [22]:
x_train=sl.fit_transform(x_train)

In [23]:
x_test=sl.transform(x_test)

In [24]:
x_train

array([[-0.8237247 ,  0.78101259, -1.01542076, ..., -0.37016353,
         0.38511259, -0.35558871],
       [-1.12597285,  0.20348166, -0.18038102, ..., -0.25743376,
         2.59920691, -0.69437982],
       [ 0.08301974, -0.85532503, -0.73707418, ...,  0.43303609,
        -0.58964592, -0.44028649],
       ...,
       [-0.8237247 , -1.36868585, -0.73707418, ...,  1.57442503,
         0.78197855, -0.86377537],
       [-1.12597285,  1.90398938,  1.21135188, ...,  1.54624258,
        -0.8054853 , -0.60968204],
       [-0.21922841,  0.23556671, -0.4587276 , ..., -0.83517383,
        -0.81592914, -0.44028649]])

In [25]:
log_r=LogisticRegression()

In [26]:
log_r.fit(x_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [27]:
y_pred=log_r.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1])

In [28]:
log_r.score(x_test,y_test)

0.8095238095238095

In [29]:
y_pred_prob = log_r.predict_proba(x_test)[:, 1]  # probabilities for ROC-AUC

In [30]:
y_pred_prob

array([0.11608907, 0.78964846, 0.6647561 , 0.14719388, 0.69624994,
       0.57929294, 0.29075674, 0.06067762, 0.12534028, 0.30217676,
       0.26292257, 0.24649702, 0.03190539, 0.12542265, 0.0816306 ,
       0.7147083 , 0.12461764, 0.44232888, 0.04503166, 0.50257353,
       0.2989442 , 0.71922551, 0.14257263, 0.36901587, 0.02942822,
       0.11400862, 0.28229206, 0.34384186, 0.06918012, 0.67658358,
       0.26511567, 0.77178929, 0.84160661, 0.2204113 , 0.1582139 ,
       0.21403584, 0.03857931, 0.69011485, 0.13603735, 0.1672728 ,
       0.39574524, 0.47129913, 0.75901653, 0.26991904, 0.03870216,
       0.10428933, 0.15013503, 0.27435995, 0.31897747, 0.32989484,
       0.08552107, 0.8227416 , 0.73522855, 0.66652652, 0.0328722 ,
       0.01589991, 0.37299733, 0.62875013, 0.82081368, 0.57064404,
       0.3004769 , 0.70884579, 0.04624136, 0.10611592, 0.04494356,
       0.07478906, 0.6842548 , 0.03725526, 0.13452411, 0.79876125,
       0.28873908, 0.43248853, 0.40070819, 0.14994481, 0.24295

In [31]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8095238095238095

In [32]:
precision = precision_score(y_test, y_pred)
precision

0.8833333333333333

In [33]:
recall = recall_score(y_test, y_pred)
recall 

0.5888888888888889

In [34]:
f1 = f1_score(y_test, y_pred)
f1 

0.7066666666666667

In [35]:
roc_auc = roc_auc_score(y_test, y_pred_prob)
roc_auc

0.8889676910953507

In [36]:
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['No Diabetes', 'Diabetes'], yticklabels=['No Diabetes', 'Diabetes'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()



In [37]:
fpr, tpr, thresholds = roc_curve(y_test, y_pred_prob)
auc_score = roc_auc_score(y_test, y_pred_prob)

In [38]:
# Plot ROC curve
plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, color='blue', label=f"ROC Curve (AUC = {auc_score:.3f})")
plt.plot([0, 1], [0, 1], color='red', linestyle=':', label='Random Guessing')
plt.title("Receiver Operating Characteristic (ROC) Curve")
plt.xlabel("False Positive Rate (1 - Specificity)")
plt.ylabel("True Positive Rate (Sensitivity)")
plt.legend()
plt.grid(True)
plt.show()

In [39]:
# INTERPRETATION
coef_df = pd.DataFrame({
    'Feature': feature.columns,
    'Coefficient': log_r.coef_[0],
    'Odds_Ratio': np.exp(log_r.coef_[0])
}).sort_values(by='Odds_Ratio', ascending=False)

print(coef_df)

                    Feature  Coefficient  Odds_Ratio
1                   Glucose     1.044902    2.843120
5                       BMI     0.580248    1.786482
0               Pregnancies     0.297415    1.346374
6  DiabetesPedigreeFunction     0.287145    1.332617
7                       Age     0.206962    1.229936
3             SkinThickness     0.062053    1.064019
4                   Insulin    -0.164065    0.848687
2             BloodPressure    -0.241238    0.785655


In [40]:
import streamlit as st
import numpy as np
import pickle

In [43]:
st.title("Diabetes Prediction App")

2025-11-03 16:47:24.303 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:24.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.


DeltaGenerator()

In [44]:
# Load saved model and scaler
log_r = pickle.load(open('logreg_model.pkl', 'rb'))
sl = pickle.load(open('sl.pkl', 'rb'))

In [45]:
st.subheader("Enter patient details")

2025-11-03 16:47:26.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:26.991 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.


DeltaGenerator()

In [46]:
pregnancies = st.number_input("Pregnancies", min_value=0, max_value=20, step=1)
glucose = st.number_input("Glucose Level", min_value=0.0, step=1.0)
blood_pressure = st.number_input("Blood Pressure (mm Hg)", min_value=0.0, step=1.0)
skin_thickness = st.number_input("Skin Thickness (mm)", min_value=0.0, step=1.0)
insulin = st.number_input("Insulin Level (mu U/ml)", min_value=0.0, step=1.0)
bmi = st.number_input("BMI", min_value=0.0, step=0.1)
dpf = st.number_input("Diabetes Pedigree Function", min_value=0.0, step=0.01)
age = st.slider("Age", 1, 100, 30)

2025-11-03 16:47:28.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:28.408 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:28.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:28.411 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:28.413 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:28.414 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:28.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:28.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bar

In [47]:
# Prepare input
input_data = np.array([[pregnancies, glucose, blood_pressure, skin_thickness, insulin, bmi, dpf, age]])
input_scaled = sl.transform(input_data)

if st.button("Predict"):
    prob = log_r.predict_proba(input_scaled)[0][1]
    result = "Diabetic" if prob > 0.5 else "Not Diabetic"

    st.subheader(f"Prediction: {result}")
    st.write(f"**Probability:** {prob:.2f}")

    if prob > 0.5:
        st.warning("High chance of diabetes. Consult a doctor.")
    else:
        st.success("Low chance of diabetes.")

2025-11-03 16:47:29.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:29.644 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:29.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:29.647 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-11-03 16:47:29.649 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.


## Interview Question

### 1. Difference between precision and recall

Precision tells you, out of all the items your model predicted as positive, how many were actually positive. It reflects how reliable the positive predictions are. High precision means the model rarely gives a positive label when it should not.

Recall tells you, out of all the actual positive cases, how many your model correctly identified. It focuses on not missing real positives. High recall means the model catches most of the true positive cases, even if it sometimes predicts positive when it should not.

In simple terms: precision cares about being accurate when saying “yes,” while recall cares about catching all the true “yes” cases.

### 2. Cross-validation and its importance in binary classification

Cross-validation is a technique where the dataset is split into multiple parts, and the model trains on some of them while being tested on the remaining part. This process rotates so every portion of data gets a chance to be used for testing. Instead of judging the model based on just one train-test split, cross-validation gives a more reliable picture of how it performs on unseen data.

In binary classification, cross-validation matters because it helps prevent overfitting and gives a fair estimate of the model’s ability to separate the two classes. It ensures that performance metrics like accuracy, precision, recall, or F1-score are trustworthy and not just the result of a lucky data split.